FROM node:18 AS build

WORKDIR /app
COPY client/package*.json ./client/
WORKDIR /app/client
RUN npm install
COPY client ./ 
RUN npm run build

FROM nginx:alpine
COPY --from=build /app/client/build /usr/share/nginx/html

EXPOSE 3000
CMD ["nginx", "-g", "daemon off;"]
